services:
  security-service:
    image: ghcr.io/${IMAGE_NAME}:latest
    container_name: security-service-reshala
    ports:
      - "8181:8181"
    environment:
      - SERVER_PORT=8181
      - SPRING_PROFILES_ACTIVE=prod

      - EUREKA_CLIENT_ENABLED=false

      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}

      - RABBIT_HOST=rabbitmq-reshala
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=${RMQ_USER}
      - RABBIT_PASSWORD=${RMQ_PASS}
      - RABBIT_VHOST=system-service

      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}

      - JWT_ACCESS_SECRET=${JWT_SECRET}
      - COOKIE_SECURE=true

    networks:
      - reshala-net
    restart: unless-stopped

networks:
  reshala-net:
    external: true