spring:
  application:
    name: security-service

  cloud:
    config:
      enabled: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:system-user}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VHOST:system-service}
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3

server:
  port: 8181
  forward-headers-strategy: native

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret:
    access: ${JWT_ACCESS_SECRET}

logging:
  level:
    root: TRACE
    org.springframework.web: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

cookie:
  secure:
    state: ${COOKIE_SECURE:false}

app:
  oauth2:
    redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:8180/api/v0/login/oauth2/code/{registrationId}}
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  geo:
    api-url: ${GEO_API_URL:http://ip-api.com/json/{ip}?lang=ru&fields=status,country,city}
  default-admin:
    email: ${DEFAULT_ADMIN_EMAIL}
    password: ${DEFAULT_ADMIN_PASSWORD}

email:
  send:
    cooldown: 1

token:
  activation:
    activate:
      ttl: 15
    resend:
      ttl: 15
  password:
    reset:
      ttl: 5
  refresh:
    isremember:
      ttl: 30d
    noremember:
      ttl: 1d

account:
  locked:
    cooldown: 5