spring:
  application:
    name: security-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5430/security_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: system-user
    password: systempass
    virtual-host: system-service
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3

  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: 5e58d1a8f2f141df8928574f01b6e152
            client-secret: 637fb18431784d97be2afc104e2786b9
            client-name: Yandex
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8180/api/v0/login/oauth2/code/{registrationId}"
            scope:
              - login:email
              - login:info
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id

server:
  port: 8181
  forward-headers-strategy: native

eureka:
  client:
    service-url:
      # Подставили юзера, пароль и хост прямо в url строки
      defaultZone: http://eureka-user:zvBGTYdMUJV7mpRs35YA@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    # Внутренние ссылки на свойства самого Spring (как spring.application.name) оставляем, они безопасны
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret:
    access: AZGEwiclv3fkxe9GYSpLdIiwbWc/AzkV1SQi3YPIiq+vIAfAzrha9Q8xv79f3G3rJRPjUf1Nn0xWZ3sNajZD7Q==

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

cookie:
  secure:
    state: false

email:
  resend:
    activated:
      time: 5

app:
  default-admin:
    username: "adminchik123"
    email: "admin@example.com"
    password: "adminTop@@#123"