spring.application.name=security-service
server.port=8181
# ????? ??? ?????????? ?????? OAuth2 ?? ????????
server.forward-headers-strategy=native

spring.cloud.config.enabled=false

//||--Eureka--||
# ?????????? ??? ??????? ?? docker-compose
eureka.client.service-url.defaultZone=http://eureka-user:zvBGTYdMUJV7mpRs35YA@discovery-service:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
# ??????? ??????? ip-address ? hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

//||--DB--||
# ???? ????? ?? ????? ??????? ? compose
spring.datasource.url=jdbc:mysql://mysql-db:3306/security_service_db
# ??????? ????? ?????????? ????? ?????????? ????????? ? compose, ?? ???? ???? ?????????? ??? ? ??.
spring.datasource.username=ETA_DBUser
spring.datasource.password=ux$kgfmpJysjHBMNhXX!jFnH9@YQp!eW
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ?? ????? ????? ?? ???????????? update, ?? ??? ?????? ??????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

//||--RabbitMQ--||
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=rmuser
spring.rabbitmq.password=rmpassword

//||--Logging--||
# ????????? ??????? ???? ??? ??????????
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
logging.level.root=INFO
logging.level.org.springframework.web=INFO

//||--YandexOAuth2--||
# ???? ?? ?????????? ?????? ??? ?????, ????? ???? ??????? ?? ? ?????????? ????????? Docker
spring.security.oauth2.client.registration.yandex.client-id=dbac46e4738740cebc99213c523a8a42
spring.security.oauth2.client.registration.yandex.client-secret=2e9012ad0d7c4c718ea8d695dc459f6e
# ... ????????? ????????? ?????????? ???????? ????????

# ???????: ?? ??????? ??????????? ????? ???? ???? ????? ?????????? JWT_SECRET_ACCESS
jwt.secret.access=${JWT_SECRET_ACCESS:dGhpcy1pcy1hLWxvY2FsLWRldi1zZWNsLyZXQtYmFzZsLTY0LWtleQ==}
cookie.secure.state=false

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized