spring:
  application:
    name: security-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5430/security_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    host: localhost
    port: 5672
    username: system-user
    password: systempass
    virtual-host: system-service
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3

server:
  port: 8181
  forward-headers-strategy: native

eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:zvBGTYdMUJV7mpRs35YA@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret:
    access: AZGEwiclv3fkxe9GYSpLdIiwbWc/AzkV1SQi3YPIiq+vIAfAzrha9Q8xv79f3G3rJRPjUf1Nn0xWZ3sNajZD7Q==

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

cookie:
  secure:
    state: false

app:
  oauth2:
    redirect-uri: http://localhost:8180/api/v0/login/oauth2/code/{registrationId}
  frontend-url: http://localhost:3000
  geo:
    api-url: http://ip-api.com/json/{ip}?lang=ru&fields=status,country,city
  default-admin:
    email: "admin@example.com"
    password: "adminTop@@#123"

email:
  send:
    cooldown: 1

token:
  activation:
    activate:
      ttl: 15
    resend:
      ttl: 15
  password:
    reset:
      ttl: 5
  refresh:
    isremember:
      ttl: 30d
    noremember:
      ttl: 1d

account:
  locked:
    cooldown: 5