spring:
  application:
    name: security-service

  cloud:
    config:
      enabled: false

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5430/security_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:system-user}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VHOST:system-service}
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3

  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: ${YANDEX_CLIENT_ID}
            client-secret: ${YANDEX_CLIENT_SECRET}
            client-name: Yandex
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - login:email
              - login:info
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id

server:
  port: 8181
  forward-headers-strategy: native

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret:
    access: ${JWT_ACCESS_SECRET}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

cookie:
  secure:
    state: ${COOKIE_SECURE:false}

email:
  resend:
    activated:
      time: 1